### ISSUE TITLE
vívoactive 3 issue can't swipe left/right

### ISSUE THREAD

**Issue by opecko** [SylvainGa/Calculator#3]
I don't know if the error is on my side, but I can't swipe left or right on my vívoactive 3

**Comment by SylvainGa** [comment]
I removed the VA3 from the list of supported devices already since it's missing the onDrag call that I'm using to detect where you swipe on screen.

**Comment by opecko** [comment]
> I removed the VA3 from the list of supported devices already since it's missing the onDrag call that I'm using to detect where you swipe on screen.

It's still there

https://github.com/SylvainGa/Calculator/assets/154607133/be54e6cd-ac14-4253-a8d8-8008f47b52b4

**Comment by SylvainGa** [comment]
That's odd. I had it removed in 1.7.3  but it went back in 1.7.4. Removed again in 1.7.5. Sorry for the trouble.
